### ISSUE TITLE
`Image*` function declarations accept the wrong pointer type

### ISSUE THREAD

**Issue by bit69tream** [ryupold/raylib.zig#10]
Image drawing and manipulating functions accept a single-item pointer to an Image type in the Raylib itself. However in these bindings they accept a many-item pointer, which is wrong.

**Comment by ryupold** [comment]
changed the default mapping of Image* to be a single item pointer as it is the usual case for most functions.
Also added the `image_drawing` example: https://github.com/ryupold/examples-raylib.zig/commit/aa4575ce5c4046d0701a9a5f55f747af12b1b421
Should be working now as expected.

**Comment by bit69tream** [comment]
Thanks! 👍🏼
