### ISSUE TITLE
Update build.zig example

### ISSUE THREAD

**Issue by Steelsmasher** [ryupold/raylib.zig#11]
Raylib 4.5 uses Zig 0.11. This uses the new *std.Build instead of *std.build.Builder.
I'm struggling to find an example build.zig that actually compiles with the newest raylib.

**Comment by ryupold** [comment]
Hm, I can still build the examples with the newest zig master build.
Did you try https://github.com/ryupold/examples-raylib.zig ?
Nevertheless you are right in that I should update that 😅
which I did in the newest commits.

**Comment by Steelsmasher** [comment]
Thanks for updating. I've just tried the examples and they're working, so I'll use those as a starting point.
