### ISSUE TITLE
raylib.zig is broken with zig master

### ISSUE THREAD

**Issue by Dimension4** [ryupold/raylib.zig#20]
https://github.com/ziglang/zig/pull/16046 breaks a lot of type casts in raylib.zig. A simple `zig fmt` fixes it. 

I'd open a PR, but this file is auto generated and I'm new to zig so I'd rather not touch it.

**Comment by ryupold** [comment]
Thanks for the issue and reminder :)
I updated to the new casting syntax so compiling should work again.
Unfortunately `json.parseFromSlice()` seems to be broken right now so i cannot update the bindings to the newest raylib master.

**Comment by ryupold** [comment]
Nevermind, I freed the memory returned from `json.parseFromSlice` too early 😅
