### ISSUE TITLE
How raylib.zig support emscripten?

### ISSUE THREAD

**Issue by TheWaWaR** [ryupold/raylib.zig#28]
Since zig [not support emscripten](https://github.com/ziglang/zig/issues/10836) yet, how can rablib.zig support it?

**Comment by ryupold** [comment]
Raylib can be build for webassembly (wasm32). There is a `PLATFORM_WEB` build flag specifically for that.
That flag basically sets a OpenGL version that is, in its API, identical to WebGL.
The Emscripten linker detects that you want to make a OpenGL call and rewrites it as WebGL call.

Emscripten is not a platform, it is a comiler toolchain.
In my [examples ](https://github.com/ryupold/examples-raylib.zig/blob/main/build.zig) you can see that I:
- compile all raylib units (rcore.c, rshapes.c, rtextures.c, etc.) with emscripten (`emcc`)
- link them all into one static library with `emar`
- build my example code with zig as static library
- link it all with `emcc`

The emscripten toolchain does its magic and generates outputs a wasm file and html/js code to show it.
There is also a .data file that contains everything in the assets folder and the files can be loaded as if they exist locally.

**Comment by TheWaWaR** [comment]
Wow, that's awesome! Quite interesting way to compile zig to emscripten.
