### ISSUE TITLE
Error in build.zig in empty project

### ISSUE THREAD

**Issue by MusinDanil** [ryupold/raylib.zig#30]
Just added submodule updated it and trying to run build.zig. However such error occures.
```
C:\Source\teofrast> zig build
C:\Source\teofrast\raylib\build.zig:101:35: error: expected struct or union; found '[]const u8'
    exe.addIncludePath(.{ .path = dir_raylib });
                                  ^~~~~~~~~~
referenced by:
    build: C:\Source\teofrast\build.zig:28:11
    runBuild__anon_7747: C:\Soft\zig-windows-x86_64-0.11.0-dev.3395+1e7dcaa3a\lib\std\Build.zig:1602:27
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

I am new to zig so i suspect i may have done something wrong. But it seems like a problem with types so my input should not influence it(maybe?).

**Comment by ryupold** [comment]
Which Version of Zig are you using. At the moment the master version works best.

**Comment by MusinDanil** [comment]
Thanks a lot! Yes i missed the fact that i was running it with 0.11. Builds ok on master.
